# Don't generate README.md
skip_docs

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.101.0"

default_platform :ios

platform :android do

  desc "Runs all the Android tests"
  lane :test do
    gradle(
      project_dir: "platforms/android",
      task: "test"
    )
  end

end

platform :ios do

  desc "Runs all the iOS tests"
  lane :test do
    scan(
      project: "platforms/ios/AppShell.xcodeproj"
    )
  end

end
